2023-01-19 14:51:14,380 INFO    MainThread:98355 [wandb_setup.py:_flush():68] Configure stats pid to 98355
2023-01-19 14:51:14,380 INFO    MainThread:98355 [wandb_setup.py:_flush():68] Loading settings from /Users/colinhoffmann/.config/wandb/settings
2023-01-19 14:51:14,380 INFO    MainThread:98355 [wandb_setup.py:_flush():68] Loading settings from /Users/colinhoffmann/Desktop/mnist/wandb/settings
2023-01-19 14:51:14,380 INFO    MainThread:98355 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-01-19 14:51:14,380 INFO    MainThread:98355 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program': '/Users/colinhoffmann/Desktop/mnist/main.py'}
2023-01-19 14:51:14,380 INFO    MainThread:98355 [wandb_init.py:_log_setup():478] Logging user logs to /Users/colinhoffmann/Desktop/mnist/wandb/run-20230119_145114-eamusxgp/logs/debug.log
2023-01-19 14:51:14,380 INFO    MainThread:98355 [wandb_init.py:_log_setup():479] Logging internal logs to /Users/colinhoffmann/Desktop/mnist/wandb/run-20230119_145114-eamusxgp/logs/debug-internal.log
2023-01-19 14:51:14,380 INFO    MainThread:98355 [wandb_init.py:init():518] calling init triggers
2023-01-19 14:51:14,380 INFO    MainThread:98355 [wandb_init.py:init():521] wandb.init called with sweep_config: {}
config: {}
2023-01-19 14:51:14,380 INFO    MainThread:98355 [wandb_init.py:init():571] starting backend
2023-01-19 14:51:14,380 INFO    MainThread:98355 [wandb_init.py:init():575] setting up manager
2023-01-19 14:51:14,383 INFO    MainThread:98355 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-01-19 14:51:14,386 INFO    MainThread:98355 [wandb_init.py:init():582] backend started and connected
2023-01-19 14:51:14,388 INFO    MainThread:98355 [wandb_init.py:init():670] updated telemetry
2023-01-19 14:51:14,406 INFO    MainThread:98355 [wandb_init.py:init():710] communicating run to backend with 60.0 second timeout
2023-01-19 14:51:15,866 INFO    MainThread:98355 [wandb_run.py:_on_init():2121] communicating current version
2023-01-19 14:51:16,436 INFO    MainThread:98355 [wandb_run.py:_on_init():2125] got version response 
2023-01-19 14:51:16,436 INFO    MainThread:98355 [wandb_init.py:init():758] starting run threads in backend
2023-01-19 14:51:19,251 INFO    MainThread:98355 [wandb_run.py:_console_start():2101] atexit reg
2023-01-19 14:51:19,251 INFO    MainThread:98355 [wandb_run.py:_redirect():1959] redirect: SettingsConsole.WRAP_RAW
2023-01-19 14:51:19,251 INFO    MainThread:98355 [wandb_run.py:_redirect():2024] Wrapping output streams.
2023-01-19 14:51:19,251 INFO    MainThread:98355 [wandb_run.py:_redirect():2046] Redirects installed.
2023-01-19 14:51:19,251 INFO    MainThread:98355 [wandb_init.py:init():798] run started, returning control to user process
2023-01-19 14:51:19,385 INFO    MainThread:98355 [wandb_watch.py:watch():51] Watching
2023-01-19 14:56:56,528 ERROR   MainThread:98355 [util.py:get_module():376] Error importing optional module plotly.tools
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/wandb/util.py", line 337, in import_module_lazy
    return sys.modules[name]
KeyError: 'plotly.tools'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/wandb/util.py", line 371, in get_module
    return import_module_lazy(name)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/wandb/util.py", line 339, in import_module_lazy
    module_spec = importlib.util.find_spec(name)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/importlib/util.py", line 94, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
ModuleNotFoundError: No module named 'plotly'
2023-01-19 14:57:03,845 WARNING MsgRouterThr:98355 [router.py:message_loop():77] message_loop has been closed
